name: TestPlugin
version: '${version}'
main: me.leopold95.testplugin.TestPlugin
api-version: '1.16'

commands:
  tchange:
    description: Команда плагина IncslusMine
    aliases:
      - tc
      - change
    usage: /<command> <args>
